Add better error message when using @function in class
egraphs-good/egglog-python pull request #230
Opened 2024-10-29 18:37 UTC by saulshanabrook

Addresses https://github.com/egraphs-good/egglog-python/issues/229 cc @shinawy hopefully this would be more helpful?

2024-12-04 06:16 UTC, hameerabbasi requested changes
Minor suggestion.

2024-12-04 06:16 UTC, hameerabbasi commented on python/egglog/egraph.py
> +            raise ValueError(f"Error processing {cls_name}.{method_name}: {e}") from e
```suggestion
            raise ValueError(f"Error processing {cls_name}.{method_name}") from e
```

The `from e` should already give the previous stack trace.

2024-12-04 06:16 UTC, hameerabbasi commented on python/egglog/egraph.py
> +            raise ValueError(f"Error processing {cls_name}.{method_name}: {e}") from e
Or explicitly pull out the message.

2024-12-04 07:27 UTC, shinawy commented
@saulshanabrook Thank you, it is better now.

2024-12-05 15:14 UTC, saulshanabrook commented on python/egglog/egraph.py
> +            raise ValueError(f"Error processing {cls_name}.{method_name}: {e}") from e
Thanks for the suggestion! I decided to keep it for now to make it easier so you don't have to find the other traceback as well.

I think just taking the string of the message does an OK job of pulling it out?

2024-12-05 15:20 UTC, merged